// Explicit projections and ownership keys reviewed against the deployed schema. Never select signing keys or OAuth tokens.
export const exportScopes: readonly { table: string; columns: string; owners: readonly string[] }[] = [
  { table: "profiles", columns: "id,is_verified,profile_views,created_at,updated_at,is_freelancer,email_digest_enabled,username,fullname,headline,bio,avatar_url,phone,location,domain,auth_type,remote_actor_url,home_instance,header_url,dm_privacy,freelancer_skills,freelancer_rate,freelancer_availability,website,contact_email", owners: ["id"] },
  { table: "experiences", columns: "id,user_id,is_current_role,start_date,end_date,created_at,updated_at,title,company,location,description,verification_status,verification_token,company_domain", owners: ["user_id"] },
  { table: "education", columns: "id,user_id,start_year,end_year,created_at,updated_at,institution,degree,field,verification_status,verification_token", owners: ["user_id"] },
  { table: "skills", columns: "id,user_id,endorsements,created_at,name", owners: ["user_id"] },
  { table: "post_replies", columns: "id,post_id,user_id,created_at,updated_at,content", owners: ["user_id"] },
  { table: "messages", columns: "id,sender_id,recipient_id,read_at,created_at,is_federated,is_encrypted,job_conversation_id,content,federated_activity_id,remote_sender_url,remote_recipient_url,delivery_status,encrypted_content,encryption_version,sender_key_fingerprint,recipient_key_fingerprint", owners: ["sender_id", "recipient_id"] },
  { table: "user_connections", columns: "id,user_id,connected_user_id,created_at,updated_at,status", owners: ["user_id", "connected_user_id"] },
  { table: "author_follows", columns: "id,follower_id,author_id,created_at,source", owners: ["follower_id", "author_id"] },
  { table: "saved_items", columns: "id,user_id,item_id,created_at,item_type", owners: ["user_id"] },
  { table: "reactions", columns: "id,target_id,user_id,created_at,updated_at,target_type,reaction", owners: ["user_id"] },
  { table: "articles", columns: "id,user_id,published,published_at,created_at,updated_at,company_id,title,content,excerpt,cover_image_url,slug,tags", owners: ["user_id"] },
  { table: "article_reactions", columns: "id,article_id,user_id,created_at,emoji", owners: ["user_id"] },
  { table: "article_authors", columns: "id,article_id,user_id,is_primary,can_edit,created_at", owners: ["user_id"] },
  { table: "notifications", columns: "id,recipient_id,actor_id,read,created_at,type,content,object_id,object_type", owners: ["recipient_id"] },
  { table: "user_blocks", columns: "id,blocker_id,blocked_user_id,created_at,reason", owners: ["blocker_id"] },
  { table: "user_consents", columns: "id,user_id,consented_at,withdrawn_at,consent_type,version", owners: ["user_id"] },
  { table: "events", columns: "id,user_id,start_date,end_date,is_online,max_attendees,created_at,updated_at,title,description,location,cover_image_url,meeting_url,visibility", owners: ["user_id"] },
  { table: "event_rsvps", columns: "id,event_id,user_id,created_at,status", owners: ["user_id"] },
  { table: "event_invitations", columns: "id,event_id,user_id,created_at,status", owners: ["user_id"] },
  { table: "cv_sections", columns: "id,user_id,content,display_order,created_at,updated_at,section_type,title", owners: ["user_id"] },
  { table: "job_posts", columns: "id,user_id,salary_min,salary_max,is_active,expires_at,created_at,updated_at,visa_sponsorship,transparency_score,company_id,title,company,description,location,remote_policy,salary_currency,employment_type,experience_level,skills,interview_process,response_time,team_size,growth_path,application_url,contact_email", owners: ["user_id"] },
  { table: "job_conversations", columns: "id,job_post_id,applicant_id,poster_id,created_at,updated_at", owners: ["applicant_id", "poster_id"] },
  { table: "poll_votes", columns: "id,poll_id,user_id,option_index,created_at", owners: ["user_id"] },
  { table: "recommendations", columns: "id,recommender_id,recipient_id,created_at,updated_at,relationship,position_at_time,content,status", owners: ["recommender_id", "recipient_id"] },
  { table: "referrals", columns: "id,referrer_id,referred_user_id,reward_claimed,created_at,converted_at,referred_email,referral_code,status", owners: ["referrer_id", "referred_user_id"] },
  { table: "profile_section_visibility", columns: "id,user_id,visibility,updated_at,section", owners: ["user_id"] },
  { table: "user_feed_preferences", columns: "id,user_id,show_reposts,show_replies,created_at,updated_at,default_feed,language_filter,muted_words", owners: ["user_id"] },
  { table: "custom_feeds", columns: "id,user_id,rules,is_public,position,created_at,updated_at,name,description,icon", owners: ["user_id"] },
  { table: "company_employees", columns: "id,company_id,user_id,employment_type,start_date,end_date,is_verified,verified_at,verified_by,created_at,updated_at,title", owners: ["user_id"] },
  { table: "company_roles", columns: "company_id,user_id,role,created_at,id", owners: ["user_id"] },
  { table: "company_followers", columns: "id,company_id,user_id,created_at", owners: ["user_id"] },
  { table: "company_claim_requests", columns: "id,company_id,requester_user_id,status,evidence,reviewed_by,reviewed_at,created_at", owners: ["requester_user_id"] },
  { table: "starter_packs", columns: "id,creator_id,is_featured,member_count,follower_count,created_at,updated_at,name,slug,description,category,cover_image_url", owners: ["creator_id"] },
  { table: "starter_pack_members", columns: "id,pack_id,user_id,added_by,added_at", owners: ["user_id"] },
  { table: "user_followed_packs", columns: "id,user_id,pack_id,followed_at", owners: ["user_id"] },
  { table: "user_settings", columns: "id,user_id,show_network_connections,created_at,updated_at,theme", owners: ["user_id"] },
  { table: "profile_views", columns: "id,profile_id,viewer_id,created_at", owners: ["viewer_id"] },
  { table: "message_requests", columns: "id,sender_id,recipient_id,created_at,responded_at,preview_text,intro_template,status", owners: ["sender_id", "recipient_id"] },
  { table: "actors", columns: "id,user_id,follower_count,following_count,created_at,updated_at,is_remote,manually_approves_followers,preferred_username,type,status,public_key,remote_actor_url,remote_inbox_url,also_known_as,moved_to", owners: ["user_id"] },
];
