export type LegalKind = "privacy" | "terms" | "cookies" | "conduct" | "instances";
type Document = { title: string; intro: string; path: string; sections: [string, string][] };
export const documents: Record<"sv" | "en", Record<LegalKind, Document>> = {
  sv: {
    privacy: { title: "Integritetspolicy", intro: "Vilka uppgifter Nolto använder, vad federation innebär och hur du utövar dina rättigheter.", path: "/privacy", sections: [
      ["Ansvar och kontakt", "Den här policyn gäller tjänsten Nolto.social. Kontakta Noltos operatör via adressen nedan om dina personuppgifter eller en begäran enligt dataskyddsförordningen. Andra servrar i fediversum drivs av självständiga operatörer och har egna villkor."],
      ["Uppgifter och ändamål", "Vi behandlar kontouppgifter för inloggning, de profiluppgifter du fyller i, publicerat innehåll, meddelanden och relationer mellan konton för att tillhandahålla tjänsten. Tekniska loggar, anmälningar och modereringsbeslut används för felsökning, säkerhet och hantering av missbruk. Profilfält som inte krävs för kontot är frivilliga. Publicera inte känsliga personuppgifter om dig själv eller andra."],
      ["Rättslig grund", "Kontohantering och de funktioner du begär behandlas för att fullgöra avtalet med dig. Säkerhet och moderering grundas på ett berättigat intresse av en fungerande och trygg tjänst, efter avvägning mot din integritet. När lag kräver behandling grundas den på en rättslig förpliktelse. Om en funktion kräver samtycke ska det inhämtas särskilt och kunna återkallas."],
      ["Offentlig profil och federation", "Profilen och offentliga inlägg kan läsas av andra. Om du aktiverar federation kan profil, profilbilder, inlägg, reaktioner och följarrelationer skickas till andra servrar via ActivityPub. Din adress, användarnamn@nolto.social, gör profilen sökbar via WebFinger. Mottagare kan finnas utanför EU/EES. Offentlig publicering är inte en garanti för att andra servrar raderar sina kopior när du ändrar eller tar bort något i Nolto."],
      ["Inloggning via Mastodon", "Väljer du Mastodon-inloggning kontaktar Nolto den server du anger och hämtar de kontouppgifter som behövs för att identifiera dig. Nolto får inte ditt Mastodon-lösenord. En behörighetstoken kan lagras krypterat på servern. Kontona förblir separata: inloggningen innebär inte att all historik eller alla privata meddelanden synkroniseras."],
      ["Leverantörer och säkerhet", "Nolto använder Supabase för bland annat databas, autentisering och filhantering. E-postfunktioner kan använda Resend. Driftleverantörer behandlar tekniska uppgifter för sina uppdrag. Federationens mottagande servrar är inte Noltos personuppgiftsbiträden. Meddelanden ska inte betraktas som totalsträckskrypterade: servern kan behöva behandla innehållet. Skicka inte information som kräver sådan sekretess."],
      ["Lagring och radering", "Kontoinnehåll sparas för att tillhandahålla kontot och de funktioner du använder. Du kan redigera eller radera innehåll och begära radering av kontot. Uppgifter som måste bevaras för rättsliga skyldigheter eller en pågående säkerhetsutredning kan behöva finnas kvar för det ändamålet. Säkerhetskopior och mottagande servrars kopior omfattas av separata lagringsförlopp; omedelbar radering över hela nätverket kan inte garanteras."],
      ["Dina rättigheter", "Du kan begära information, tillgång, rättelse, radering, begränsning och, när förutsättningarna är uppfyllda, dataportabilitet. Du kan invända mot behandling som grundas på berättigat intresse och återkalla samtycke. Kontakta oss via adressen nedan; vi kan behöva kontrollera din identitet utan att begära mer än nödvändigt. Du kan också lämna klagomål till Integritetsskyddsmyndigheten, imy.se."],
    ]},
    terms: { title: "Användarvillkor", intro: "Ramarna för ditt konto, ditt innehåll och samspelet med andra servrar.", path: "/terms", sections: [
      ["Ditt konto", "Nolto är ett professionellt nätverk. Du ska vara minst 16 år för att använda tjänsten. Skydda dina inloggningsuppgifter och använd tvåfaktorsautentisering när det är möjligt. Utge dig inte för att vara någon annan eller företräda en organisation utan rätt att göra det. Kontakta oss om du misstänker att någon kommit åt ditt konto."],
      ["Ditt innehåll", "Du behåller rättigheterna till material du publicerar. Du ger Nolto den icke-exklusiva rätt att lagra, visa och överföra materialet som behövs för de funktioner du använder, inklusive federation när den är aktiverad. Du ansvarar för att du får publicera materialet och att du respekterar andras integritet och rättigheter."],
      ["En adress i fediversum", "En Nolto-adress är en social identitet, inte en e-postadress. När den publicerats i federationen behöver den vara beständig. Mastodon och andra tjänster har egna konton och regler. Att följa ett konto, importera en följlista eller flytta följare innebär inte att all kontodata, inläggshistorik och privata meddelanden flyttas eller hålls synkroniserade."],
      ["Moderering och överklagande", "Trakasserier, hot, hat, bedrägerier, spam och olagligt innehåll är inte tillåtna. Nolto kan begränsa innehåll, konton eller kontakt med andra servrar vid missbruk. Vi eftersträvar proportionerliga åtgärder och en begriplig motivering där den kan lämnas utan att försvåra säkerhet eller rättsliga skyldigheter. Anmäl via tjänstens funktioner eller kontakta oss. Du kan begära att ett beslut omprövas genom att beskriva beslutet och skälen för din invändning."],
      ["Tillgänglighet och ansvar", "Tjänsten kan behöva avbrytas för underhåll eller på grund av fel. Jobbannonser, erbjudanden och uppgifter från användare behöver kontrolleras av den som använder dem. Dessa villkor begränsar inte rättigheter som följer av tvingande lag och innebär ingen utfästelse om en viss drifttid eller full kompatibilitet med varje extern server."],
      ["Avslut och ändringar", "Du kan sluta använda tjänsten och begära att kontot raderas. Offentligt material som redan tagits emot av andra kan finnas kvar hos dem. Väsentliga villkorsändringar ska meddelas innan de börjar gälla när det är möjligt. Den gällande versionen och dess revisionsdatum finns på denna sida."],
    ]},
    cookies: { title: "Cookies och lokal lagring", intro: "Vad webbläsaren sparar när du använder Nolto.", path: "/cookies", sections: [
      ["Inloggning", "Supabase-klienten sparar sessionsuppgifter i webbläsarens localStorage så att du kan förbli inloggad. Dessa uppgifter används vid autentiserade anrop till tjänsten. De är alltså inte enbart information som stannar i din webbläsare. Logga ut på delade enheter."],
      ["Inställningar och tillfälliga uppgifter", "Nolto sparar bland annat språk, tema och vissa gränssnittsinställningar lokalt. Mastodon-inloggningen använder sessionStorage för att knyta återkomsten till det inloggningsförsök du startade. En inbjudningskod kan lagras tillfälligt, med 24 timmars giltighet. Du kan radera webbplatsdata i webbläsaren; då kan du behöva logga in och göra om inställningar."],
      ["Tredje parter", "Koden innehåller ingen annonseringsspårning eller Google Analytics. Drift- och säkerhetsleverantörer kan använda teknisk lagring beroende på driftsättningen. När du hämtar externa bilder eller följer en extern länk kan din webbläsare kontakta en annan tjänst, vars egna regler gäller där. Samtycke ska inhämtas innan eventuell lagring som kräver det aktiveras."],
    ]},
    conduct: { title: "Uppförandekod", intro: "Det ska gå att mötas, samarbeta och vara oense utan att bli utsatt.", path: "/code-of-conduct", sections: [
      ["Bemöt människor sakligt", "Kritisera gärna idéer och beslut. Trakasserier, hot, diskriminerande påhopp, sexuella närmanden utan samtycke och samordnade angrepp är inte tillåtna. Respektera när någon inte vill fortsätta en kontakt."],
      ["Var tydlig med avsändare och avsikt", "Utge dig inte för att vara någon annan. Märk kommersiella erbjudanden och rekrytering så att syftet framgår. Undvik massutskick, vilseledande annonser och påhittade meriter. Automatisering ska inte användas för att spamma eller manipulera synlighet."],
      ["Skydda andras uppgifter", "Publicera inte privata kontaktuppgifter, konversationer eller känsliga personuppgifter utan rätt att göra det. Respektera upphovsrätt. Länka till källor när det hjälper andra att bedöma ett påstående."],
      ["Anmäl och begär omprövning", "Använd anmälningsfunktionen eller kontakta oss med en länk och en kort beskrivning. Du behöver inte ta en offentlig konflikt för att anmäla. Om en åtgärd berör dig kan du be om en förklaring och omprövning. Andra servrar har egna moderatorer; Nolto kan begränsa kontakten med en server men styr inte dess innehåll."],
    ]},
    instances: { title: "Instansriktlinjer", intro: "Ansvar för dig som driver en egen installation eller ansluter en server.", path: "/instance-guidelines", sections: [
      ["En självständig tjänst", "En egen installation behöver en tydlig operatör, kontaktväg, egna villkor och en dataskyddsbedömning. Att använda Noltos kod innebär inte att Nolto.social ansvarar för installationen eller garanterar dess säkerhet. Följ repositoryts licens."],
      ["Beständig identitet", "Välj en domän för federerade identiteter innan konton publiceras. WebFinger, aktörsdokument, nyckelidentifierare och signaturer måste ange samma beständiga identitet. En vanlig omdirigering av hemsidan är inte tillräcklig för att upprätthålla federation."],
      ["Drift och moderering", "Operatören ansvarar för uppdateringar, åtkomstkontroll, nycklar, säkerhetskopior, återställningsprov och uppföljning av leveransfel. Ha rutiner för anmälningar, blockerade servrar och incidenter. Skicka inte privata uppgifter som offentliga ActivityPub-objekt."],
      ["Kompatibilitet", "Testa upptäckt, följningar, publicering, redigering och radering mot en separat federerad server före öppning. AT Protocol och ActivityPub är olika protokoll; stöd för det ena ger inte automatiskt stöd för det andra. Beskriv de funktioner som faktiskt fungerar."],
    ]},
  },
  en: {
    privacy: { title: "Privacy policy", intro: "The data Nolto uses, what federation shares, and your rights.", path: "/privacy", sections: [
      ["Responsibility and contact", "This policy applies to Nolto.social. Contact its operator at the address below about personal data or a data protection request. Other federated servers have independent operators and their own policies."],
      ["Data and purposes", "We process account credentials, the profile details you provide, content, messages and account relationships to provide the service. Technical logs, reports and moderation decisions support security, troubleshooting and abuse prevention. Optional profile fields are voluntary. Do not publish sensitive personal data about yourself or others."],
      ["Legal bases", "Account management and requested features rely on performing our agreement with you. Security and moderation rely on a legitimate interest in operating a safe service, balanced against your privacy. Legal obligations may require additional processing. Where a feature requires consent, it must be requested separately and be withdrawable."],
      ["Public content and federation", "Profiles and public posts can be read by others. Enabling federation allows profile data, images, posts, reactions and account relationships to be sent to other servers using ActivityPub. WebFinger makes username@nolto.social discoverable. Recipients may be outside the EU/EEA. Editing or deleting content in Nolto cannot guarantee that every recipient deletes its copy."],
      ["Mastodon sign-in", "When you choose Mastodon sign-in, Nolto contacts that server to identify your account. Nolto does not receive your Mastodon password. An authorization token may be stored encrypted on the server. Signing in does not merge accounts or synchronize all history and private messages."],
      ["Providers and security", "Nolto uses Supabase for database, authentication and file services. Email features may use Resend. Hosting providers process technical data for their tasks. Independent federated servers are not Nolto's data processors. Messages must not be treated as end-to-end encrypted: the server may process their contents."],
      ["Retention and rights", "Account content is kept to provide the features you use. You can edit or delete content and request account deletion. Legal obligations or an ongoing security investigation may require limited retention for that purpose. Backups and remote copies follow separate retention processes. You may request access, correction, erasure, restriction and, where applicable, portability, object to legitimate-interest processing, and withdraw consent. Contact us below; proportionate identity verification may be needed. You may complain to the Swedish Authority for Privacy Protection at imy.se."],
    ]},
    terms: { title: "Terms of service", intro: "Your account, your content and independent federated servers.", path: "/terms", sections: [
      ["Your account", "Nolto is a professional network for people aged 16 and above. Protect your credentials and use two-factor authentication where possible. Do not impersonate others or represent an organization without authority. Contact us if your account may have been compromised."],
      ["Your content", "You retain your rights to your content. You grant Nolto the non-exclusive permission to store, display and transmit it as needed for the features you use, including federation when enabled. You are responsible for having the right to publish it and respecting others' privacy and rights."],
      ["Federated identity", "A Nolto address is a social identity, not an email address. Once published, it needs to remain stable. Mastodon and other services have separate accounts and rules. Following an account, importing follows or moving followers does not transfer or synchronize all data, history or private messages."],
      ["Moderation and review", "Harassment, threats, hate, fraud, spam and illegal content are prohibited. Nolto may restrict content, accounts or federation in response to abuse. We aim for proportionate action and an understandable explanation where safety and legal duties permit. Report issues in the service or contact us. You may ask for a decision to be reviewed and explain why you disagree."],
      ["Availability, closure and changes", "Maintenance and faults may interrupt the service. Verify user-provided job adverts and offers independently. These terms do not limit mandatory legal rights or promise specific uptime or compatibility with every server. You may stop using the service and request account deletion; remote copies may remain. Material changes should be communicated before taking effect where possible."],
    ]},
    cookies: { title: "Cookies and local storage", intro: "What your browser stores when you use Nolto.", path: "/cookies", sections: [
      ["Sessions", "The Supabase client stores session credentials in localStorage to keep you signed in. They are used to authenticate requests to the service, rather than remaining exclusively on your device. Sign out on shared devices."],
      ["Preferences and temporary data", "Nolto stores language, theme and some interface preferences locally. Mastodon sign-in uses sessionStorage to bind the callback to your sign-in attempt. A referral code may be retained with a 24-hour expiry. Clearing site data may require signing in and selecting preferences again."],
      ["Other services", "The application code does not include advertising tracking or Google Analytics. Hosting and security providers may use technical storage depending on the deployment. External images and links may contact other services with their own policies. Consent must be obtained before enabling any storage that requires it."],
    ]},
    conduct: { title: "Code of conduct", intro: "Space to collaborate and disagree without harassment.", path: "/code-of-conduct", sections: [
      ["Treat people respectfully", "Challenge ideas and decisions. Do not harass, threaten, discriminate, make unwanted sexual advances or organize attacks. Respect a request to stop contacting someone."],
      ["Be clear and honest", "Do not impersonate others. Make commercial offers and recruitment intentions clear. Avoid mass messaging, misleading advertisements, fabricated qualifications and automated manipulation."],
      ["Respect privacy and rights", "Do not publish private contact details, conversations or sensitive personal information without a right to do so. Respect copyright and cite sources where they help others assess a claim."],
      ["Report and appeal", "Use the report feature or contact us with a link and short description. You may request an explanation and review of action affecting you. Remote servers have their own moderators; Nolto can restrict federation but cannot control their content."],
    ]},
    instances: { title: "Instance guidelines", intro: "Responsibilities for operators of independent installations.", path: "/instance-guidelines", sections: [
      ["Independent operation", "An installation needs an identified operator, a contact channel, its own terms and a data protection assessment. Using Nolto's code does not make Nolto.social responsible for your installation or guarantee its security. Follow the repository license."],
      ["Stable identity", "Choose the federation domain before publishing accounts. WebFinger, actor documents, key identifiers and signatures must use consistent permanent identities. Redirecting the website alone does not preserve federation."],
      ["Operation and compatibility", "Maintain updates, access controls, signing keys, backups, recovery tests and delivery monitoring. Establish abuse and incident procedures. Test discovery, follows, publishing, editing and deletion against a separate server before opening. ActivityPub and AT Protocol are distinct; describe the interoperability actually available."],
    ]},
  },
};
