export type LegalKind = "privacy" | "terms" | "cookies" | "conduct" | "instances";
export const legalOperator = "Jonatan Tensetti";
type Document = { title: string; intro: string; path: string; sections: [string, string][] };
export const documents: Record<"sv" | "en", Record<LegalKind, Document>> = {
  sv: {
    privacy: { title: "Integritetspolicy", intro: "Vilka uppgifter Nolto använder, vad federation innebär och hur du utövar dina rättigheter.", path: "/privacy", sections: [
      ["Ansvar och kontakt", `${legalOperator} driver Nolto.social och är personuppgiftsansvarig för behandlingen av personuppgifter inom tjänsten. Kontakta operatören via e-postadressen nedan om dina personuppgifter eller en begäran enligt dataskyddsförordningen. Andra servrar i fediversum drivs av självständiga operatörer som ansvarar för sin egen behandling av personuppgifter och har egna villkor.`],
      ["Uppgifter och ändamål", "Vi behandlar e-postadress och autentiseringsuppgifter för inloggning, de frivilliga profilfält du fyller i, innehåll och kontakter för de funktioner du använder. Vi säljer inte personuppgifter. Vi registrerar inte profilbesök och lagrar inte meddelandetext i kontaktförfrågningar. Samtyckesposter och begäran om MFA-återställning innehåller inte IP-adress eller webbläsaridentifiering. Driftleverantörer kan fortfarande behandla tekniska anslutningsuppgifter. Säkerhetsloggar och modereringsärenden används för att skydda tjänsten och hantera anmälningar."],
      ["Rättslig grund", "Kontohantering och de funktioner du begär behandlas för att fullgöra avtalet med dig. Säkerhet och moderering grundas på ett berättigat intresse av en fungerande och trygg tjänst, efter avvägning mot din integritet. När lag kräver behandling grundas den på en rättslig förpliktelse. Om en funktion kräver samtycke ska det inhämtas särskilt och kunna återkallas."],
      ["Offentlig profil och federation", "Profilen och offentliga inlägg kan läsas av andra. Om du aktiverar federation kan profil, profilbilder, inlägg, reaktioner och följarrelationer skickas till andra servrar via ActivityPub. Din adress, användarnamn@nolto.social, gör profilen sökbar via WebFinger. Mottagare kan finnas utanför EU/EES. Offentlig publicering är inte en garanti för att andra servrar raderar sina kopior när du ändrar eller tar bort något i Nolto."],
      ["Inloggning via Mastodon", "Väljer du Mastodon-inloggning kontaktar Nolto den server du anger och hämtar de kontouppgifter som behövs för att identifiera dig. Nolto får inte ditt Mastodon-lösenord. En behörighetstoken kan lagras krypterat på servern. Kontona förblir separata: inloggningen innebär inte att all historik eller alla privata meddelanden synkroniseras."],
      ["Leverantörer och säkerhet", "Backend drivs i Lovable Cloud med Supabase-teknik för databas, autentisering och filer. E-post kan skickas genom Resend. Leverantörerna behöver behandla vissa uppgifter för driften. Andra federerade servrar är självständiga operatörer. Offentliga profiler, inlägg och filer måste vara läsbara för tjänsten och mottagande servrar. Krypterad överföring och kryptering med servernyckel är inte helsträckskryptering och eliminerar inte risken för intrång."],
      ["Privata meddelanden", "Nya privata meddelanden mellan Nolto-konton helsträckskrypteras och signeras i webbläsaren. Båda behöver aktivera sin krypterade inkorg. Nyckelfrasen skickas inte till Nolto; den privata nyckeln sparas enbart i krypterad form. En upplåst nyckel används i webbläsarens minne och låses vid utloggning, sidans stängning eller 15 minuters inaktivitet. Avsändare, mottagare och tidpunkter är fortfarande synliga för servern. Äldre meddelanden markeras separat och kan dekrypteras av servern. Offentligt innehåll och meddelanden på andra tjänster omfattas inte. Spara nyckelfras och krypterad nyckelbackup säkert: ett återställt kontolösenord återställer inte nyckelfrasen. Jämför nycklarnas fingeravtryck via en annan betrodd kanal. En angripare som kontrollerar din enhet eller tjänstens levererade programkod kan fortfarande komma åt innehåll när du använder inkorgen."],
      ["Lagring och radering", "När du begär att radera ett konto, inlägg, en kommentar eller artikel döljs det direkt i Noltos vanliga gränssnitt och API. För konton spärras åtkomsten samtidigt. Permanent radering är schemalagd till 30 dagar efter begäran. Under väntetiden är uppgifterna avskilda från vanlig åtkomst; innehållsarkivet krypteras med en separat servernyckel och filer flyttas till ett privat, krypterat arkiv av bakgrundsjobbet. Det är inte helsträckskryptering. Inloggningens begränsningslogg gallras efter ett dygn, federationsloggar efter sju dagar och MFA-återställningsärenden efter 30 dagar. Begränsade identifikatorer kan behållas för att markera raderade federationsobjekt och förhindra att någon tar över en gammal federationsadress. Säkerhetskopior hos driftleverantörer och kopior som mottagare redan har hämtat kan finnas kvar enligt andra förlopp. En begäran enligt GDPR prövas utan onödigt dröjsmål och kan kräva tidigare radering; 30-dagarsflödet begränsar inte dina rättigheter. Kontakta oss om en skyndsam eller mer omfattande radering behövs."],
      ["Dina rättigheter", "Du kan begära information, tillgång, rättelse, radering, begränsning och, när förutsättningarna är uppfyllda, dataportabilitet. Du kan invända mot behandling som grundas på berättigat intresse och återkalla samtycke. Kontakta oss via adressen nedan; vi kan behöva kontrollera din identitet utan att begära mer än nödvändigt. Du kan också lämna klagomål till Integritetsskyddsmyndigheten, imy.se."],
    ]},
    terms: { title: "Användarvillkor", intro: "Ramarna för ditt konto, ditt innehåll och samspelet med andra servrar.", path: "/terms", sections: [
      ["Tjänstens operatör", `Nolto har skapats av ${legalOperator}, som också driver tjänsten Nolto.social. Dessa villkor gäller mellan dig och tjänstens operatör. Du når operatören via e-postadressen under Kontakt.`],
      ["Ditt konto", "Nolto är ett professionellt nätverk. Du ska vara minst 16 år för att använda tjänsten. Skydda dina inloggningsuppgifter och använd tvåfaktorsautentisering när det är möjligt. Utge dig inte för att vara någon annan eller företräda en organisation utan rätt att göra det. Kontakta oss om du misstänker att någon kommit åt ditt konto."],
      ["Ditt innehåll", "Du behåller rättigheterna till material du publicerar. Du ger Nolto den icke-exklusiva rätt att lagra, visa och överföra materialet som behövs för de funktioner du använder, inklusive federation när den är aktiverad. Du ansvarar för att du får publicera materialet och att du respekterar andras integritet och rättigheter."],
      ["En adress i fediversum", "En Nolto-adress är en social identitet, inte en e-postadress. När den publicerats i federationen behöver den vara beständig. Mastodon och andra tjänster har egna konton och regler. Att följa ett konto, importera en följlista eller flytta följare innebär inte att all kontodata, inläggshistorik och privata meddelanden flyttas eller hålls synkroniserade."],
      ["Moderering och överklagande", "Trakasserier, hot, hat, bedrägerier, spam och olagligt innehåll är inte tillåtna. Nolto kan begränsa innehåll, konton eller kontakt med andra servrar vid missbruk. Vi eftersträvar proportionerliga åtgärder och en begriplig motivering där den kan lämnas utan att försvåra säkerhet eller rättsliga skyldigheter. Anmäl via tjänstens funktioner eller kontakta oss. Du kan begära att ett beslut omprövas genom att beskriva beslutet och skälen för din invändning."],
      ["Tillgänglighet och ansvar", "Tjänsten kan behöva avbrytas för underhåll eller på grund av fel. Jobbannonser, erbjudanden och uppgifter från användare behöver kontrolleras av den som använder dem. Dessa villkor begränsar inte rättigheter som följer av tvingande lag och innebär ingen utfästelse om en viss drifttid eller full kompatibilitet med varje extern server."],
      ["Avslut och ändringar", "Du kan sluta använda tjänsten och begära att kontot raderas. Offentligt material som redan tagits emot av andra kan finnas kvar hos dem. Väsentliga villkorsändringar ska meddelas innan de börjar gälla när det är möjligt. Den gällande versionen och dess revisionsdatum finns på denna sida."],
    ]},
    cookies: { title: "Cookies och lokal lagring", intro: "Vad webbläsaren sparar när du använder Nolto.", path: "/cookies", sections: [
      ["Meddelandenycklar", "Webbläsaren sparar nyckelfingeravtryck för att upptäcka nyckelbyten. Varken nyckelfrasen eller upplåsta privata nycklar sparas i lokal lagring. Rensad webbläsarlagring tar bort tidigare jämförelser; kontrollera då fingeravtrycken igen."],
      ["Inloggning", "Supabase-klienten sparar sessionsuppgifter i webbläsarens localStorage så att du kan förbli inloggad. Dessa uppgifter används vid autentiserade anrop till tjänsten. De är alltså inte enbart information som stannar i din webbläsare. Logga ut på delade enheter."],
      ["Inställningar och tillfälliga uppgifter", "Nolto sparar bland annat språk, tema och vissa gränssnittsinställningar lokalt. Mastodon-inloggningen använder sessionStorage för att knyta återkomsten till det inloggningsförsök du startade. En inbjudningskod kan lagras tillfälligt, med 24 timmars giltighet. Du kan radera webbplatsdata i webbläsaren; då kan du behöva logga in och göra om inställningar."],
      ["Tredje parter", "Koden innehåller ingen annonseringsspårning eller Google Analytics. Drift- och säkerhetsleverantörer kan använda teknisk lagring beroende på driftsättningen. När du hämtar externa bilder eller följer en extern länk kan din webbläsare kontakta en annan tjänst, vars egna regler gäller där. Samtycke ska inhämtas innan eventuell lagring som kräver det aktiveras."],
    ]},
    conduct: { title: "Uppförandekod", intro: "Det ska gå att mötas, samarbeta och vara oense utan att bli utsatt.", path: "/code-of-conduct", sections: [
      ["Bemöt människor sakligt", "Kritisera gärna idéer och beslut. Trakasserier, hot, diskriminerande påhopp, sexuella närmanden utan samtycke och samordnade angrepp är inte tillåtna. Respektera när någon inte vill fortsätta en kontakt."],
      ["Var tydlig med avsändare och avsikt", "Utge dig inte för att vara någon annan. Märk kommersiella erbjudanden och rekrytering så att syftet framgår. Undvik massutskick, vilseledande annonser och påhittade meriter. Automatisering ska inte användas för att spamma eller manipulera synlighet."],
      ["Skydda andras uppgifter", "Publicera inte privata kontaktuppgifter, konversationer eller känsliga personuppgifter utan rätt att göra det. Respektera upphovsrätt. Länka till källor när det hjälper andra att bedöma ett påstående."],
      ["Anmäl och begär omprövning", "Använd anmälningsfunktionen eller kontakta oss med en länk och en kort beskrivning. Du behöver inte ta en offentlig konflikt för att anmäla. Om en åtgärd berör dig kan du be om en förklaring och omprövning. Andra servrar har egna moderatorer; Nolto kan begränsa kontakten med en server men styr inte dess innehåll."],
    ]},
    instances: { title: "Instansriktlinjer", intro: "Ansvar för dig som driver en egen installation eller ansluter en server.", path: "/instance-guidelines", sections: [
      ["En självständig tjänst", "En egen installation behöver en tydlig operatör, kontaktväg, egna villkor och en dataskyddsbedömning. Att använda Noltos kod innebär inte att Nolto.social ansvarar för installationen eller garanterar dess säkerhet. Följ repositoryts licens."],
      ["Beständig identitet", "Välj en domän för federerade identiteter innan konton publiceras. WebFinger, aktörsdokument, nyckelidentifierare och signaturer måste ange samma beständiga identitet. En vanlig omdirigering av hemsidan är inte tillräcklig för att upprätthålla federation."],
      ["Drift och moderering", "Operatören ansvarar för uppdateringar, åtkomstkontroll, nycklar, säkerhetskopior, återställningsprov och uppföljning av leveransfel. Ha rutiner för anmälningar, blockerade servrar och incidenter. Skicka inte privata uppgifter som offentliga ActivityPub-objekt."],
      ["Kompatibilitet", "Testa upptäckt, följningar, publicering, redigering och radering mot en separat federerad server före öppning. AT Protocol och ActivityPub är olika protokoll; stöd för det ena ger inte automatiskt stöd för det andra. Beskriv de funktioner som faktiskt fungerar."],
    ]},
  },
  en: {
    privacy: { title: "Privacy policy", intro: "The data Nolto uses, what federation shares, and your rights.", path: "/privacy", sections: [
      ["Responsibility and contact", `${legalOperator} operates Nolto.social and is the data controller for personal data processed as part of this service. Contact the operator at the email address below about personal data or a data protection request. Other federated servers have independent operators who are responsible for their own processing of personal data and have their own policies.`],
      ["Data and purposes", "We process your account email and authentication data, the optional profile fields you supply, content and relationships to provide the features you use. We do not sell personal data. We do not track profile visits or store message previews in contact requests. Consent records and MFA recovery requests do not retain IP addresses or browser identifiers. Hosting providers may still process technical connection information. Security logs and moderation records are used to protect the service and handle reports."],
      ["Legal bases", "Account management and requested features rely on performing our agreement with you. Security and moderation rely on a legitimate interest in operating a safe service, balanced against your privacy. Legal obligations may require additional processing. Where a feature requires consent, it must be requested separately and be withdrawable."],
      ["Public content and federation", "Profiles and public posts can be read by others. Enabling federation allows profile data, images, posts, reactions and account relationships to be sent to other servers using ActivityPub. WebFinger makes username@nolto.social discoverable. Recipients may be outside the EU/EEA. Editing or deleting content in Nolto cannot guarantee that every recipient deletes its copy."],
      ["Mastodon sign-in", "When you choose Mastodon sign-in, Nolto contacts that server to identify your account. Nolto does not receive your Mastodon password. An authorization token may be stored encrypted on the server. Signing in does not merge accounts or synchronize all history and private messages."],
      ["Providers and security", "The backend runs on Lovable Cloud using Supabase technology for database, authentication and files. Email may use Resend. Providers process information needed for operation. Other federated servers have independent operators. Public profiles, posts and files must be readable by the service and receiving servers. Encryption in transit and encryption using a server key are not end-to-end encryption and cannot eliminate the risk of a breach."],
      ["Private messages", "New private messages between Nolto accounts are encrypted and signed in the browser. Both participants must activate their encrypted inbox. The key phrase is never sent to Nolto; the private key is backed up only in encrypted form. An unlocked key is held in browser memory and locked on sign-out, page exit or 15 minutes of inactivity. Sender, recipient and timestamps remain visible to the server. Older messages are labelled separately and can be decrypted by the server. Public content and messages on other services are excluded. Keep your key phrase and encrypted key backup safe: resetting your account password does not recover the key phrase. Compare key fingerprints through another trusted channel. An attacker controlling your device or the code delivered by the service may still access content while you use the inbox."],
      ["Retention and rights", "Requesting deletion of an account, post, comment or article hides it immediately from Nolto’s ordinary interface and API. Account access is disabled at the same time. Permanent deletion is scheduled for 30 days after the request. During that period data is isolated from ordinary access; retained content is encrypted with a separate server key and a background job moves files to a private encrypted archive. This is not end-to-end encryption. Authentication rate-limit logs are pruned after one day, federation logs after seven days and MFA recovery requests after 30 days. Limited identifiers may be kept as federation tombstones and to prevent takeover of a retired federation address. Provider backups and copies already downloaded by recipients follow separate processes. GDPR requests are assessed without undue delay and may require earlier erasure; the 30-day workflow does not restrict your rights. Contact us if urgent or broader erasure is needed."],
      ["Your rights", "You may request access, correction, erasure, restriction and, where applicable, portability, object to legitimate-interest processing and withdraw consent. Contact us below; proportionate identity verification may be needed. You may complain to the Swedish Authority for Privacy Protection at imy.se."],
    ]},
    terms: { title: "Terms of service", intro: "Your account, your content and independent federated servers.", path: "/terms", sections: [
      ["Service operator", `Nolto was created by ${legalOperator}, who also operates Nolto.social. These terms apply between you and the service operator. You can reach the operator at the email address under Contact.`],
      ["Your account", "Nolto is a professional network for people aged 16 and above. Protect your credentials and use two-factor authentication where possible. Do not impersonate others or represent an organization without authority. Contact us if your account may have been compromised."],
      ["Your content", "You retain your rights to your content. You grant Nolto the non-exclusive permission to store, display and transmit it as needed for the features you use, including federation when enabled. You are responsible for having the right to publish it and respecting others' privacy and rights."],
      ["Federated identity", "A Nolto address is a social identity, not an email address. Once published, it needs to remain stable. Mastodon and other services have separate accounts and rules. Following an account, importing follows or moving followers does not transfer or synchronize all data, history or private messages."],
      ["Moderation and review", "Harassment, threats, hate, fraud, spam and illegal content are prohibited. Nolto may restrict content, accounts or federation in response to abuse. We aim for proportionate action and an understandable explanation where safety and legal duties permit. Report issues in the service or contact us. You may ask for a decision to be reviewed and explain why you disagree."],
      ["Availability, closure and changes", "Maintenance and faults may interrupt the service. Verify user-provided job adverts and offers independently. These terms do not limit mandatory legal rights or promise specific uptime or compatibility with every server. You may stop using the service and request account deletion; remote copies may remain. Material changes should be communicated before taking effect where possible."],
    ]},
    cookies: { title: "Cookies and local storage", intro: "What your browser stores when you use Nolto.", path: "/cookies", sections: [
      ["Message keys", "The browser stores key fingerprints to detect key changes. The key phrase and unlocked private keys are not written to local storage. Clearing browser storage removes prior comparisons; verify fingerprints again afterwards."],
      ["Sessions", "The Supabase client stores session credentials in localStorage to keep you signed in. They are used to authenticate requests to the service, rather than remaining exclusively on your device. Sign out on shared devices."],
      ["Preferences and temporary data", "Nolto stores language, theme and some interface preferences locally. Mastodon sign-in uses sessionStorage to bind the callback to your sign-in attempt. A referral code may be retained with a 24-hour expiry. Clearing site data may require signing in and selecting preferences again."],
      ["Other services", "The application code does not include advertising tracking or Google Analytics. Hosting and security providers may use technical storage depending on the deployment. External images and links may contact other services with their own policies. Consent must be obtained before enabling any storage that requires it."],
    ]},
    conduct: { title: "Code of conduct", intro: "Space to collaborate and disagree without harassment.", path: "/code-of-conduct", sections: [
      ["Treat people respectfully", "Challenge ideas and decisions. Do not harass, threaten, discriminate, make unwanted sexual advances or organize attacks. Respect a request to stop contacting someone."],
      ["Be clear and honest", "Do not impersonate others. Make commercial offers and recruitment intentions clear. Avoid mass messaging, misleading advertisements, fabricated qualifications and automated manipulation."],
      ["Respect privacy and rights", "Do not publish private contact details, conversations or sensitive personal information without a right to do so. Respect copyright and cite sources where they help others assess a claim."],
      ["Report and appeal", "Use the report feature or contact us with a link and short description. You may request an explanation and review of action affecting you. Remote servers have their own moderators; Nolto can restrict federation but cannot control their content."],
    ]},
    instances: { title: "Instance guidelines", intro: "Responsibilities for operators of independent installations.", path: "/instance-guidelines", sections: [
      ["Independent operation", "An installation needs an identified operator, a contact channel, its own terms and a data protection assessment. Using Nolto's code does not make Nolto.social responsible for your installation or guarantee its security. Follow the repository license."],
      ["Stable identity", "Choose the federation domain before publishing accounts. WebFinger, actor documents, key identifiers and signatures must use consistent permanent identities. Redirecting the website alone does not preserve federation."],
      ["Operation and compatibility", "Maintain updates, access controls, signing keys, backups, recovery tests and delivery monitoring. Establish abuse and incident procedures. Test discovery, follows, publishing, editing and deletion against a separate server before opening. ActivityPub and AT Protocol are distinct; describe the interoperability actually available."],
    ]},
  },
};
