/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3372baeba61eb483687222ab3b56ebe9)
interface __BaseEnv_Env {
	GATEWAY_MODE: "route";
	FEDERATION_DOMAIN: "nolto.social";
	SUPABASE_ORIGIN: "https://anknmcmqljejabxbeohv.supabase.co";
	ATPROTO_DID: "";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./nolto-gateway");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GATEWAY_MODE" | "FEDERATION_DOMAIN" | "SUPABASE_ORIGIN" | "ATPROTO_DID">> {}
}
