-- Tracking marker for the managed deployment on 22 September 2026.
-- The platform applied a copy of 20260922172019_post_image_drafts.sql
-- under this generated version. The canonical version is also recorded in production.
-- Keep this version for history reconciliation; execute schema changes only in
-- the earlier canonical migration so a fresh replay cannot create tables twice.
